all:
    apps_name:      Singapore Quality Records    
    page_heading:   Singapore Quality Records     
    menu:
        items:        
            - ['HOME',              'home',       'index']         
#            - ['GENERAL GARMENT',                 'generalGarment',       'index']
#            - ['TECH GARMENT SYSTEM',             'techGarment',       'index']
            - ['QUALITY RECORDS',                 'micronclean',       'index']
            - ['TRAINING RECORDS',                'training',       'index']

    ampie:
        public_path: /sg/qualityRecord/js/ampie/
        public_swf: /sg/qualityRecord/js/ampie/ampie.swf
    amline:
        public_path: /sg/qualityRecord/js/amline/
        public_swf: /sg/qualityRecord/js/amline/amline.swf
    amcolumn:
        public_path: /sg/qualityRecord/js/amcolumn/
        public_swf: /sg/qualityRecord/js/amcolumn/amcolumn.swf
        
    path_iso9000:           /opt/httpd/htdocs_i/uploads/iso9000/AUDIT SCHEDULE/          
	
    email:
        smtp_mode:  true
#        smtp_server:    mail5.cybersite.com.sg
#        smtp_username:  microncleanservice@micronclean.com.sg
#        smtp_password:  email123senoko
        smtp_server:    10.10.10.3
        smtp_username:  
        smtp_password:  
        
        attachment_size_limit:  10
        
        from_default:           Micronclean Online
        from_address_default:   microncleanservice@micronclean.com.sg
        cclist:                 mcsloggerx@yahoo.com
        debug_address:          mcslogger@yahoo.com   
        debug_address_local:    mcslogger@yahoo.com 