<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/12/03 09:04:28
sfConfig::add(array(
  'app_apps_name' => 'Singapore Quality Records',
  'app_page_heading' => 'Singapore Quality Records',
  'app_menu_items' => array (
  0 => 
  array (
    0 => 'HOME',
    1 => 'home',
    2 => 'index',
  ),
  1 => 
  array (
    0 => 'QUALITY RECORDS',
    1 => 'micronclean',
    2 => 'index',
  ),
  2 => 
  array (
    0 => 'TRAINING RECORDS',
    1 => 'training',
    2 => 'index',
  ),
),
  'app_ampie_public_path' => '/sg/qualityRecord/js/ampie/',
  'app_ampie_public_swf' => '/sg/qualityRecord/js/ampie/ampie.swf',
  'app_amline_public_path' => '/sg/qualityRecord/js/amline/',
  'app_amline_public_swf' => '/sg/qualityRecord/js/amline/amline.swf',
  'app_amcolumn_public_path' => '/sg/qualityRecord/js/amcolumn/',
  'app_amcolumn_public_swf' => '/sg/qualityRecord/js/amcolumn/amcolumn.swf',
  'app_path_iso9000' => '/opt/httpd/htdocs_i/uploads/iso9000/AUDIT SCHEDULE/',
  'app_email_smtp_mode' => true,
  'app_email_smtp_server' => '10.10.10.3',
  'app_email_smtp_username' => NULL,
  'app_email_smtp_password' => NULL,
  'app_email_attachment_size_limit' => 10,
  'app_email_from_default' => 'Micronclean Online',
  'app_email_from_address_default' => 'microncleanservice@micronclean.com.sg',
  'app_email_cclist' => 'mcsloggerx@yahoo.com',
  'app_email_debug_address' => 'mcslogger@yahoo.com',
  'app_email_debug_address_local' => 'mcslogger@yahoo.com',
));
