<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/12/03 09:04:33
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
